name: PR Checks

on:
  workflow_dispatch: # manually trigger workflow
#   pull_request: # pr against main (pr opened, commits to pr)
#     branches:
#       - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")" >> $GITHUB_ENV

      - name: Restore Playwright binaries
        uses: actions/cache/restore@v4 # only restores / do not saves cache -- we do that separately in cache.yml
        id: playwright-cache 
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Run Playwright UI tests
        run: npm run test
